# BLOG SETTINGS
title: "I'd Rather Be Writing - Tom Johnson"
name: "I'd Rather Be Writing Blog"
description: Technical writing blog focusing on the latest trends, news, and other topics in the field of technical communication.
media: https://s3.us-west-1.wasabisys.com/idbwmedia.com/
host: 127.0.0.1
port: 4000
feedback_email: tomjoht@gmail.com
sidebar_accordion: true
output: web
paginate: 15
timezone: America/Los_Angeles
blog_logo_file: bloglogo_bloglogo.svg
media: https://s3.us-west-1.wasabisys.com/idbwmedia.com/images
# API DOC SETTINGS
api_title: Documenting APIs
api_description: A guide for technical writers and engineers working with APIs
api_site_logo_file: learnapidoclogo-01.svg
# bloglogo_apidoclogo.svg
api_language: english
api_sidebar: docapis
api_media: https://s3.us-west-1.wasabisys.com/idbwmedia.com/images/api

# Link to home
url: https://idratherbewriting.com
baseurl:

destination: _site
highlighter: rouge
exclude:
  - ebooks
  - pdf
format: web

plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true
  restapicourse:
    output: true
  publishingapidocs:
    output: true
  voiceovertechniques:
    output: true
  visualcommunication:
    output: true
  podcasts:
    output: true
  youngadultnovel:
    output: false
  user_centered_doc:
    output: true
sass:
    style: compressed

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      topnav: topnav
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
      topnav: topnav
      comments: true
      search: true
      author: <a href='/aboutme/'>Tom Johnson</a>
  -
    scope:
      path: ""
      type: "tooltips_demo"
    values:
      layout: "page"
      search: true
  -
    scope:
      path: ""
      type: "podcasts"
    values:
      layout: "itunes"

  -
    scope:
      path: ""
      type: "visualcommunication"
    values:
      layout: "page_visualcommunication"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: docs
    values:
      layout: default
      sidebar: docapis
      topnav: topnav
      progress: true
      permalink: /docs:path.html
  -
    scope:
      path: "images"
    values:
      image: true

########## UI text ###############

uistring:
    tableofcontents: Table of Contents
    log_doc_issue: Log Doc Issue
    breadcrumb:
      home: Home
      documentation: Documentation
    expandall: Expand All
    collapseall: Collapse All
    title: Learn API Doc # Displays as site title on top nav bar and on site metadata
    description: A guide for technical writers and engineers learning how to document APIs  # Displays as site description meta
    github_edit_button_text: Edit on GitHub
    products: Products
    docindex_product: Product
    docindex_startpage: Starting page


####### Algolia configuration ###########
algolia:
  application_id: XUM0ZBII9L
  index_name: idratherbewriting
  search_only_api_key: aa11df1f45809fcdfb5b7bc89a301682
  files_to_exclude:
    - ./toc.html
    - _docs/pdf_frontmatter/*
    - _docs/introduction_to_rest_apis/tocstart.html
    - _docs/introduction_to_rest_apis/tocstart_fulldetails.md
    - _docs/activities_pdf/*
    - _docs/slides/*
    - _drafts
    - .idea
    - _site
    - vendor
    - redirects/*
    - files/**/*
    - pages/category-archives/*
    - pages/date-based-archives/*
  nodes_to_index: 'p,.description'

eventbrite_public_token: FUQRFCCTNLYIUXJZQCSV
####### jekyll seo tag configuration #######
title: Documenting APIs
tagline: A guide for technical writers and engineers learning how to document APIs
description: Online course about creating API documentation, mostly focusing on REST APIs but covering strategies for developer documentation in general. Includes sections on what an API is, API reference documentation, OpenAPI specification and Swagger, docs-as-code publishing and workflows, conceptual topics, tutorials, API documentation jobs, and more.
url: https://idratherbewriting.com
author:
  twitter: tomjohnson
twitter:
  username: tomjohnson
  card: summary

logo: https://s3.us-west-1.wasabisys.com/idbwmedia.com/images/idratherbewriting-site-logo.png

social:
  name: Tom Johnson
  links:
    - https://twitter.com/tomjohnson
    - https://www.facebook.com/tomidbw
    - https://www.linkedin.com/in/tomjoht/
    - https://github.com/tomjoht

facebook:
  app_id: 247143161970549
  publisher: 3968842976464

webmaster_verifications:
  google: i1qwK1LFgKEQHUtpm8o7OOOeK9i54NUQwKR4vXRqlFs
  bing: 352636FE6BAFC693A6938983FC6A227E

lang: en_US
