scope: all
title: Documenting REST APIs
subtitle: "A guide for technical writers and engineers creating API documentation"
api_media: /Users/tomjoht/projects/idratherbewriting/images/api
# cover: true
# if cover is set to true, the title and subtitle aren't used. instead, the cover_image is used instead.
cover_image: images/ebook_cover.png

sidebar: docapis
baseurl: /Users/tomjoht/projects/idratherbewriting/_site

language: english
format: print

destination: _site
port: 4000
highlighter: rouge
exclude:
  - ebooks
  - pdf

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true
  slides:
    output: false
  pages:
    output: false

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: printpdf
  -
    scope:
      path: ""
      type: docs
    values:
      layout: printpdf
      published: true

  -
    scope:
      path: _docs/pdf_frontmatter
      type: docs
    values:
      layout: printpdf
      published: true
